### ISSUE TITLE
instructions on how to build and run this?

### ISSUE THREAD

**Issue by pmahnke** [letrend/v4l2-ctl-gui#1]
I am not familiar on how to build and run an ncurses programme.  Can you provide help in the readme?

**Comment by luizhdinizf** [comment]
i need it too

**Comment by luizhdinizf** [comment]
if using ubuntu:
sudo apt-get install libncurses5-dev
sudo apt install cmake-curses-gui

go to downloaded directory and type
ccmake CMakeLists.txt 
then press [c] and the [g]
then type make

**Comment by pmahnke** [comment]
thanks @luizhdinizf that worked for me.
